#cloud-config
users:
  - default
  - name: nutanix
    gecos: Nutanix User
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo
chpasswd:
  expire: false
  users:
  - name: nutanix
    password: nutanix/4u
    type: text
ssh_pwauth: True
package_upgrade: true
package_reboot_if_required: true
locale: en_US.UTF-8
timezone: America/Chicago
packages:
  - git
runcmd:
  - sudo git clone https://github.com/ericgullickson/voting-app.git /home/nutanix/voting-app/
  - echo 'nutanix:nutanix/4u' | sudo chpasswd