# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    build: 
      context: ./vote
      target: dev
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
     - ./vote:/usr/local/app
    ports:
      - "80:80"
    environment:
      - DB=${DB}
      - WORKER=${WORKER}
      - VOTE=${VOTE}
      - RESULT=${RESULT}
      - REDIS=${REDIS}
    extra_hosts:
      - db:${DB}
      - worker:${WORKER}
      - vote:${VOTE}
      - result:${RESULT}
      - redis:${REDIS}
